$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [1]:
import numpy as np

In [4]:
# ベクトルの定義
x = np.array([[1],[2],[3]])
x

array([[1],
       [2],
       [3]])

In [7]:
# 行列の定義
X = np.array([[1,2], [3,4]])
X

array([[1, 2],
       [3, 4]])

In [9]:
Xt = X.T
Xt

array([[1, 3],
       [2, 4]])

In [11]:
X_inv = np.linalg.inv(X)
X_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [13]:
XX_inv = np.dot(X, X_inv)
XX_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [16]:
X.shape

(2, 2)

# 演習問題
$
\boldsymbol{X} = \left[
                    \begin{array}{rrr}
                      1 & 2 & 3 \\
                      1 & 2 & 5 \\
                      1 & 3 & 4 \\
                      1 & 5 & 9
                    \end{array}
                  \right]
, \boldsymbol{y} = \left[
                    \begin{array}{rrr}
                      1 \\
                      5 \\
                      6 \\
                      8
                    \end{array}
                  \right]
$ のとき

$
\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}
$

- STEP1: $\boldsymbol{X}^{T}\boldsymbol{X}$
- STEP2: $(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}$
- STEP3: $\boldsymbol{X}^{T}\boldsymbol{y}$
- STEP4: $\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [18]:
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9],
])
X

array([[1, 2, 3],
       [1, 2, 5],
       [1, 3, 4],
       [1, 5, 9]])

In [21]:
y = np.array([
    [1],
    [5],
    [6],
    [8],
])
y

array([[1],
       [5],
       [6],
       [8]])

In [23]:
XtX = np.dot(X.T, X)
XtX

array([[  4,  12,  21],
       [ 12,  42,  73],
       [ 21,  73, 131]])

In [25]:
XtX_inv = np.linalg.inv(XtX)
XtX_inv

array([[ 1.76530612, -0.39795918, -0.06122449],
       [-0.39795918,  0.84693878, -0.40816327],
       [-0.06122449, -0.40816327,  0.24489796]])

In [28]:
Xty = np.dot(X.T, y)
Xty

array([[ 20],
       [ 70],
       [124]])

In [30]:
w = np.dot(XtX_inv, Xty)
w

array([[-0.14285714],
       [ 0.71428571],
       [ 0.57142857]])

# Scikit-learn

In [31]:
import sklearn

In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
model = LinearRegression()

In [34]:
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [36]:
model.intercept_

array([-0.14285714])

In [37]:
model.score(X,y)

0.6923076923076923

In [38]:
x = np.array([
    [1,2,3]
])

In [39]:
model.predict(x)

array([[3.]])